name: Build_Latest
 
on:
  push:
    branches:
      - master
      - new
      - main
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
     
    - name: Restore NuGet Packages
      run: nuget restore PDF_Password_Remover.sln
 
    - name: Build 
      run: msbuild PDF_Password_Remover.sln /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=None
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: PDF_Password_Remover_latest
        path: bin\Release\
